services:
    caddy:
        build: .
        container_name: project-reader-caddy
        restart: always
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - default
            - proxy-net
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

networks:
    proxy-net:
        external: true

volumes:
    caddy_data:
    caddy_config:
