name: Deploy to Server

on:
    push:
        branches:
            - master

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Copy files to Server
              uses: appleboy/scp-action@v1.0.0
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: ".,!node_modules/**,!.svelte-kit/**,!build/**"
                  target: "~/apps/project-reader"

            - name: Execute Docker Compose on Server
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd ~/apps/project-reader
                      docker compose up --build --remove-orphans -d
